version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo Installing system dependencies...
      - yum update -y
      - yum install -y curl git unzip php-cli php-mbstring php-xml php-pdo php-common php-dev
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer

  pre_build:
    commands:
      - echo Cloning repository...
      - git clone https://github.com/javie611/RecipeHub480.git app
      - cd app
      - echo Installing PHP dependencies...
      - composer install --no-dev --optimize-autoloader
      - chmod -R 775 storage bootstrap/cache

  build:
    commands:
      - echo Running Laravel setup...
      - php artisan config:cache
      - php artisan migrate --force

    post_build:
    commands:
      - echo Deploying application to /var/www/html/...
      - rm -rf /var/www/html/*
      - git clone https://github.com/javie611/RecipeHub480.git /var/www/html/
      - cd /var/www/html
      - composer install --no-dev --optimize-autoloader
      - chmod -R 775 storage bootstrap/cache
      - php artisan config:cache
      - php artisan migrate --force
      - echo Deployment completed successfully.


artifacts:
  files:
    - '**/*'
