name: Deploy Laravel to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

env:
      STACK_NAME: recipehub-stack
      REGION: us-east-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Wait for EC2s to initialize
        run: sleep 60

      - name: Get EC2 public IPs
        id: get_ips
        run: |
          IP1=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=EC2_1" \
                      "Name=instance-state-name,Values=running" \
            --query "Reservations[*].Instances[*].PublicIpAddress" \
            --region $REGION --output text)

          IP2=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=EC2_2" \
                      "Name=instance-state-name,Values=running" \
            --query "Reservations[*].Instances[*].PublicIpAddress" \
            --region $REGION --output text)

          echo "EC2_1_IP=$IP1" >> $GITHUB_ENV
          echo "EC2_2_IP=$IP2" >> $GITHUB_ENV

      - name: Deploy Laravel to EC2_1
        run: |
          echo "Deploying to $EC2_1_IP"
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} ec2-user@$EC2_1_IP 'bash -s' < ./deploy.sh

      - name: Deploy Laravel to EC2_2
        run: |
          echo "Deploying to $EC2_2_IP"
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} ec2-user@$EC2_2_IP 'bash -s' < ./deploy.sh
