name: Update to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Update to EC2 Instances
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ec2-18-116-211-64.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
          ssh-keyscan -H ec2-3-14-227-89.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2 Instance 1
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-18-116-211-64.us-east-2.compute.amazonaws.com << 'EOF'
            cd /var/www/html/RecipeHub480
            git config --global --add safe.directory /var/www/html/RecipeHub480
            sudo git pull origin main
          EOF

      - name: Deploy to EC2 Instance 2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-3-14-227-89.us-east-2.compute.amazonaws.com << 'EOF'
            cd /var/www/html/RecipeHub480
            git config --global --add safe.directory /var/www/html/RecipeHub480
            sudo git pull origin main
          EOF
