name: Deploy Laravel to AWS

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: 'The environment to deploy to (e.g., production, staging)'
        required: true
        default: 'production'
      deploy_ami:
        description: 'Create a new AMI before deploying? (yes/no)'
        required: false
        default: 'yes'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      STACK_NAME: recipehub-stack
      REGION: us-east-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Create New AMI and Update CloudFormation
        run: |
          INSTANCE_ID="i-0c1a09c9025af84fc"
          AMI_NAME="AMI-Updated-$(date +'%Y-%m-%d-%H-%M-%S')"
          echo "Creating a new AMI from instance: $INSTANCE_ID"
          NEW_AMI_ID=$(aws ec2 create-image --instance-id $INSTANCE_ID --name "$AMI_NAME" --no-reboot --output text)
          echo "New AMI ID: $NEW_AMI_ID"
          echo "Waiting for the AMI to become available..."
          aws ec2 wait image-available --image-ids $NEW_AMI_ID
          echo "AMI $NEW_AMI_ID is now available."
          echo "Updating CloudFormation template with new AMI ID: $NEW_AMI_ID"
          sed -i "s|<NEW_AMI_ID>|$NEW_AMI_ID|g" template.yaml
          echo "AMI creation, CloudFormation update, and cleanup complete."

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides KeyName="web server key" HostedZoneId=Z082369723XCVMCYY5MYD
               
      - name: Wait for EC2s to initialize
        run: sleep 60

      - name: Revert template.yaml back to placeholder
        run: |
          echo "Reverting template.yaml back to <NEW_AMI_ID>..."
          sed -i "s|ami-[a-zA-Z0-9]*|<NEW_AMI_ID>|g" template.yaml

      - name: Deployed Laravel
        run: |
          echo "Application deployed, ready for traffic"
